[toc]

## np.meshgrid
np.meshgrid 是 NumPy 中的一个函数，用于生成多维坐标网格。它常用于创建多维函数的坐标网格，比如在三维绘图或等高线绘制中。这个函数接受一维数组作为输入，然后返回一个多维数组，其中包含了根据输入数组的值生成的所有可能的坐标点。以下是一个简单的示例：

In [2]:
import numpy as np

# 定义一维数组作为 x 和 y 坐标
x = np.array([0, 1, 2])
y = np.array([3, 4, 5])

# 使用 meshgrid 函数生成二维坐标网格
X, Y = np.meshgrid(x, y)

print("X 坐标网格：")
print(X)
print("Y 坐标网格：")
print(Y)

X 坐标网格：
[[0 1 2]
 [0 1 2]
 [0 1 2]]
Y 坐标网格：
[[3 3 3]
 [4 4 4]
 [5 5 5]]


## np.c_
np.c_ 是 NumPy 中的一个类，用于按列连接两个数组。它可以将两个一维数组按列连接成一个二维数组。以下是一个简单的示例：

In [4]:
import numpy as np

# 定义两个一维数组
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 使用 np.c_ 函数将两个数组按列连接成一个二维数组
result = np.c_[a, b]

print("连接后的结果：")
print(result)

连接后的结果：
[[1 4]
 [2 5]
 [3 6]]


## ravel()
ravel() 函数是 NumPy 中的一个方法，用于将多维数组展平为一维数组。它返回的是数组的视图，因此对返回的一维数组的修改会影响原始数组。以下是一个简单的示例：

In [6]:
import numpy as np

# 创建一个二维数组
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# 使用 ravel() 方法将数组展平为一维数组
flattened_arr = arr.ravel()

print("展平后的数组：")
print(flattened_arr)

展平后的数组：
[1 2 3 4 5 6]


In [9]:
np.c_[X.ravel(), Y.ravel()]

array([[0, 3],
       [1, 3],
       [2, 3],
       [0, 4],
       [1, 4],
       [2, 4],
       [0, 5],
       [1, 5],
       [2, 5]])